### ISSUE TITLE
Not aligned between FP32 and INT8 

### ISSUE THREAD

**Issue by BossunWang** [Tencent/TNN#1057]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: linux

  **2. Github版本**
 - branch：master
 - commit(optional): 6dc2d935069c12cba083e308b6c2f43d69f0c831

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型不对齐（model misalignment）
 - original model： ONNX
 - models: https://drive.google.com/file/d/1GAwpKgbRS9UiLi1qVQz3-r1vaFR6Y9ro/view?usp=sharing

Hi, experts,
I test between ONNX and fp 32 which precision error between e-4 ~ e-5, cos distance 1.0, that's OK.
But when I do quantization to INT8,  precision error between e+1 ~ e-1, cos distance 0.25, that's so bad.

May you help me to check what's wrong about my model? Thanks you first.
 
same issue:
https://github.com/Tencent/TNN/issues/945

**Comment by quinnrong94** [comment]
@BossunWang The problem seems to be the same as #1017. The branch hotfix_issue_1017 fixes some error of the quantization tool. You can checkout to that branch,  compile the quantization tool and then re-quantize your model.

**Comment by BossunWang** [comment]
not solved, Do you have any ONNX model I would like to test the precision whether I can know the standard range?

**Comment by quinnrong94** [comment]
@BossunWang  Take the model you updated as an example, and use just one picture to quantize the model. The results of fp32 model and int8 model are similar, with cosine distance larger than 99%:
> (512,)  vs  (512,)
[cosine distance]  [0.997857717] = 0.502907/(0.715926*0.703965) [max_diff: 0.006060] outputs/out_fp32.out vs outputs/out_int8.out

The quantization and test scripts are attached:
[scripts.zip](https://github.com/Tencent/TNN/files/6723673/scripts.zip)

You need to change `PathToQuantCmd` and `PathToTNNTest` in `run.sh` to real pathes in your system, and put the original model.opt.tnnproto and model.opt.tnnmodel in tnn sub-folder.

Since branch hotfix_issue_1017 has been merged into master, the results are obtained using branch master with commit id ca26a1b5.

Be careful to set scale and bias consistently for quantization and inference.
Refer to https://github.com/Tencent/TNN/blob/master/doc/en/user/quantization_en.md for more details of quantization parameters and https://github.com/Tencent/TNN/blob/master/doc/en/user/api_en.md#matconvertparam-description for MatConvertParam in inference.

**Comment by BossunWang** [comment]
Hi, experts
I build version of commit you said and got same result from your script.
But when I change to use pytorch resnet 101 to generate int8 model, the cosine distance lower than yours
`(1000,)  vs  (1000,)
[cosine distance]  [0.944611395] = 14025.254070/(128.386835*115.647717) [max_diff: 7.337965] outputs/out_fp32.out vs outputs/out_int8.out`
Is it any parameter should be change for different models?
https://drive.google.com/file/d/1kMBXejltY74Hqcu3SSwlDbTFH9skhdPS/view?usp=sharing

**Comment by BossunWang** [comment]
I change the parameters which from https://pytorch.org/vision/stable/models.html:
-s 0.01712475383,0.0175070028,0.01742919389
-n 123.675,116.28,103.53

Do you have any other model as reference which you test pass on release version?
I would like to know your precision compared with MNN and NCNN.
For example pytoch model zoo:
https://pytorch.org/vision/stable/models.html

**Comment by quinnrong94** [comment]
@BossunWang Both images and parameters should be consistent with training process, in this way, we expect cosine distance up to 0.95 or higher by our previous experience.
We have successfully deployed some quantized models for many businesses using TNN, with acceptable precision loss. If you still have a specific problem on quantizing your model, please provide more details and we are very welling to help.

**Comment by BossunWang** [comment]
"successfully deployed some quantized models for many businesses using TNN"
May you shared this model and quantization parameter for me to check my situation?

**Comment by quinnrong94** [comment]
@BossunWang Here is an example of quantizing resnet, which may help you set your quantization parameter.
[resnet.zip](https://github.com/Tencent/TNN/files/6782308/resnet.zip)
You can follow the step in run.sh. The expected cosine distance of int8 and fp32 results is 0.996, which is tested on master branch with commit id 2e9e97cc. For simplicity, the preprocess of input image follows: (data / 255.0 - 0.456) / 0.224.
The docker image used to convert onnx model to tnn model is turandotkay/tnn-convert:latest on Docker Hub. Since the latest convert tool will generate tnn models that support dynamic dims, the latest tnn on master branch is prefered in such case.

**Comment by BossunWang** [comment]
Hi expert,
Tanks your model for me to compared with the resnet architecture.
I find out the first problem, my architecture can't convert to TNN without -optimize on convert.py step.
But the other model which one is your resnet and insightface passed without -optimize.
https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch
the following is debbug message:

> D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /workspace/TNN_Bossun_build/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 375] weight = output_layer.0.running_var

> D/converter:` int Onnx2TNN::OnnxExtractBlobWeights() [File /wpython3: /workspace/TNN_Bossun_build/TNN/tools/onnx2tnn/src/core/onnx_utility.cc:523: int get_tensor_proto_data_size(const onnx::TensorProto&): Assertion `0' failed.

> Aborted (core dumped)

This is my model

https://drive.google.com/file/d/1akbHKdGtqEmmXcEtZglXm8B8cX3-cxPm/view?usp=sharing
