### ISSUE TITLE
instance.net init failed 8192

### ISSUE THREAD

**Issue by sherlockgjh** [Tencent/TNN#42]
请问，模型初始化，显示的instance.net init failed 8192，是什么错误呢？

**Comment by sherlockgjh** [comment]
我通过打印description()显示是：0x2000 msg: not support mode type，但model_type设置的是MODEL_TYPE_TNN，模型转为TNN模型：分别为*.opt.tnnmodel和*.opt.tnnproto，这个错误是模型转换问题导致吗？

**Comment by shaundai-tencent** [comment]
使用模型转换工具转换成功后，模型应该不会有问题。这个问题有可能是编译tnn的时候配置有问题，导致TNN模型解析器没有注册成功。是编译的静态库还是动态库？

-------------------
shaundai(戴冠雄)
腾讯-优图实验室

发件人: sherlockgjh [mailto:notifications@github.com]
发送时间: 2020年6月11日 11:28
收件人: Tencent/TNN <TNN@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Tencent/TNN] instance.net init failed 8192 (#42)(Internet mail)


我通过打印description()显示是：0x2000 msg: not support mode type，但model_type设置的是MODEL_TYPE_TNN，模型转为TNN模型：分别为*.opt.tnnmodel和*.opt.tnnproto，这个错误是模型转换问题导致吗？

**Comment by sherlockgjh** [comment]
我使用的是静态库

**Comment by shaundai-tencent** [comment]
在链接静态库的时候需要加-Wl,--whole-archive TNN -Wl,--no-whole-archive

-------------------
shaundai(戴冠雄)
腾讯-优图实验室

发件人: sherlockgjh [mailto:notifications@github.com]
发送时间: 2020年6月11日 11:44
收件人: Tencent/TNN <TNN@noreply.github.com>
抄送: shaundai(戴冠雄) <shaundai@tencent.com>; Comment <comment@noreply.github.com>
主题: Re: [Tencent/TNN] instance.net init failed 8192 (#42)(Internet mail)


我使用的是静态库

**Comment by sherlockgjh** [comment]
谢谢，已调试通过，运行正常了。android端目前只有OpenCL加速吗？期待可以支持更多的方式。

**Comment by shaundai-tencent** [comment]
还有ARM CPU的加速。

-------------------
shaundai(戴冠雄)
腾讯-优图实验室

发件人: sherlockgjh [mailto:notifications@github.com]
发送时间: 2020年6月11日 18:18
收件人: Tencent/TNN <TNN@noreply.github.com>
抄送: shaundai(戴冠雄) <shaundai@tencent.com>; Comment <comment@noreply.github.com>
主题: Re: [Tencent/TNN] instance.net init failed 8192 (#42)(Internet mail)


谢谢，已调试通过，运行正常了。android端目前只有OpenCL加速吗？期待可以支持更多的方式。

**Comment by zhangwei147258** [comment]
I also meet the same problem, but it does not compile sussfully when add "-Wl,--whole-archive TNN -Wl,--no-whole-archive",  because it can not find TNN.
this is my Andoroid.mk，I do not kown where the problem is.


LOCAL_PATH := $(call my-dir)

TNN_INSTALL_PATH := ${LOCAL_PATH}/tnn-android-lib

include $(CLEAR_VARS)
LOCAL_MODULE := TNN
LOCAL_SRC_FILES := $(TNN_INSTALL_PATH)/arm64-v8a/libTNN.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := faceDetectTNN
LOCAL_C_INCLUDES += $(TNN_INSTALL_PATH)/include \
                    $(TNN_INSTALL_PATH)/include/tnn \
                    ${LOCAL_PATH}/samples

LOCAL_SRC_FILES += zeewain_face_detection_tnn_demo.cc \
                    helper_jni.cc \
                    samples/TNNSDKSample.cc \
                    samples/UltraFaceDetector.cc
LOCAL_STATIC_LIBRARIES := TNN

LOCAL_CPPFLAGS := -O2 -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math
LOCAL_LDFLAGS += -Wl,--whole-archive TNN -Wl,--no-whole-archive

LOCAL_LDLIBS := -lz -llog -ljnigraphics -landroid

include $(BUILD_SHARED_LIBRARY)
