### ISSUE TITLE
Benchmark from shell 4 threads runs slower than 1 thread on qualcomm 855 CPU.

### ISSUE THREAD

**Issue by lee-bin** [Tencent/TNN#981]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM

  **2. Github版本**
 - branch：master
 - commit(optional):aba45f8a965fc44a9cb8a61ec48859667085486f

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)
./benchmark_models.sh -th 4 -t CPU -bs

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```
No build error.

  **5. 详细描述bug 情况 (Describe the bug)**
./benchmark_models.sh -th 4 -t CPU -bs
runs slower than 
./benchmark_models.sh -th 1 -t CPU -bs
The device is qualcomm 855. The mobilenetv1 benchmark from shell CPU 4 threads avg latency is 37ms, 1 thread avg latency is 29ms. However, if benchmark from app, 4 threads avg latency is 10ms, 1 thread avg latency is 29ms which is normal. I guess it's related to 855's super big core as the latency is normal if running on 835.

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```

**Comment by powerpwang** [comment]
The poor performance of 4 threads may be caused by the scheduling policy of system.
If running benchmark_models.sh scripts, TNNTest won't set thread affinity. Then system will schedule multi-threads by default, which may schedule 4 threads on little cores or big cores with poor performance. You can use some profiling tools to check which cores have been used.
You can also modify benchmark_models.sh scripts by adding "-dl" option to tell TNNTest to set affinity manually.
For example, ./TNNTest -th ${THREAD_NUM} -dl 4,5,6,7
(4th, 5th, 6th, 7th cores of 855 are 3 big cores + 1 super core)

BTW, the schedule policy of benchmark-from-shell may also be different from benchmark-from-app.

**Comment by lee-bin** [comment]
@powerpwang Thanks, I modified the codes to set thread affinity and got better performance (10ms).
Another quick question, would TNN fully utilize all 8 cores to achieve better performance than 4 big cores?
I tried it, it performed worse than 4 big cores (27ms). I assume it is related to OpenMP's task schedule policy?
Is this expected for TNN?

**Comment by powerpwang** [comment]
This is expected. In this case, schedule policy may have an effect on performance, since fully utilizing all cores costs more power and system doesn't want this happen, but it's not the main reason.
The main reason is the load imbalance issue between different cores. It's difficult to achieve load balance among big cores and little cores, you need to divide parallel tasks very carefully. Thus, we only expect we can get speed up among homogeneous cores, for example, 4 threads on 4 little cores, or 4 threads on 4 big cores.

**Comment by lee-bin** [comment]
@powerpwang Great, thank you very much!
